timezone: America/New_York

teams:
  - id: audubon-north
    name: Audubon North
    urls:
      - https://www.eriemetrosports.com/schedule/team_instance/10191173?subseason=945400
  - id: harborcenter-549836
    name: Harborcenter Team 549836
    urls:
      - https://www.rinksatharborcenter.com/stats#/1367/team/549836/schedule