name: Build Hockey ICS Feeds

on:
  schedule:
    - cron: "17 10 * * *"  # daily at 10:17 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Build ICS feeds
        run: |
          python -c "from src.main import build_team_feeds; build_team_feeds()"

      - name: Commit updated docs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/ || true
          git commit -m "Update ICS feeds [skip ci]" || echo "No changes"
          git push